

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict

from astevolve.search.operator_registry import default_operator_weights


_BASE_STRATEGY: Dict[str, Any] = {
    "preferred_edit_order": [],
    "iterations": 1200,
    "init_temp": 2.0,
    "cooling": 0.995,
    "mutation_rate": 0.06,
    "resample_segment_prob": 0.08,
    "mutation_ops": default_operator_weights("node", profile="base"),
    "search_method": "mcts",
    "mcts_c_puct": 1.4,
    "mcts_max_depth": 4,
    "mcts_reward_scale": 1.0,
    "mcts_iteration_unit": "expansion_rounds",
    "mcts_candidate_budget_max_round_multiplier": 4,
    "mcts_candidate_budget_fail_on_underfill": True,
    "mcts_progressive_widening_c": 2.0,
    "mcts_progressive_widening_alpha": 0.5,
    "proposal_tier_mode": "fixed_node",
    "mcts_output_dir": "inner_loop",
    "mcts_save_tree": True,
    "mcts_save_variants": True,
    "mcts_tree_quality_required": False,
    "mcts_tree_min_root_children": 0,
    "mcts_tree_min_branching_nodes": 0,
    "mcts_tree_min_leaves": 0,
    "mcts_tree_min_max_depth": 0,
    "outer_loop_phase": "explore_ast",
    "search_schedule": {
        "enabled": True,
        "phase_policy": "explore_ast broadens AST/search-space edits; refine_ast balances repair and exploitation; converge narrows edits and increases inner-loop precision.",
        "phases": {},
    },
    "progen_weight": 1.0,
    "sequence_prior_model": "progen",
    "inner_structure_enabled": True,
    "inner_structure_model": "esmfold2",
    "inner_structure_model_name": None,
    "inner_structure_weight": 1.0,
    "inner_structure_fail_closed": True,
    "inner_structure_hard_gate": True,
    "inner_structure_failure_penalty": 1000.0,
    "inner_esmfold2_enabled": False,
    "inner_esmfold2_model_name": None,
    "inner_esmfold2_interval": 10,
    "inner_esmfold2_weight": 1.0,
    "mcts_node_sweep_enabled": False,
    "mcts_node_sweep_count": 0,
    "mcts_node_sweep_parent_policy": "incumbent",
    "mcts_fidelity_upgrade_enabled": False,
    "mcts_fidelity_upgrade_provider": "protenix",
    "mcts_fidelity_upgrade_interval": 20,
    "mcts_fidelity_upgrade_candidates": 4,
    "mcts_fidelity_upgrade_final_candidates": 5,
    "mcts_fidelity_upgrade_required": False,
    "node_optimizer_enabled": False,
    "node_optimizer_candidate_count": 8,
    "node_optimizer_beam_width": 16,
    "node_optimizer_top_k_per_position": 4,
    "node_optimizer_temperature": 0.8,
    "node_optimizer_diversity_weight": 0.15,
    "node_optimizer_mutation_penalty": 0.25,
    "node_optimizer_prior_model": "heuristic",
    "structure_model": "protenix",
    "structure_model_name": None,
    "structure_prescreen_enabled": False,
    "structure_prescreen_model": "esmfold2",
    "structure_prescreen_model_name": None,
    "structure_prescreen_top_frac": 1.0,
    "structure_prescreen_min_candidates": 1,
    "structure_prescreen_max_candidates": 0,
    "structure_prescreen_forward_all_to_screen": False,
    "protenix_conda_env": "pytorch",
    "esmfold2_mode": "local",
    "esmfold2_conda_env": None,
    "esmfold2_num_loops": 3,
    "esmfold2_num_sampling_steps": 32,
    "esmfold2_num_diffusion_samples": 1,
    "multistate_objectives_enabled": True,
    "multistate_objective_weight": 1.0,
    "chai1_enabled": True,
    "chai1_top_frac": 0.01,
    "chai1_min_candidates": 1,
    "chai1_max_candidates": 3,
    "history_size": 50,
    "max_hydrophobic_run": 2,
    "max_charged_run": 2,
    "score_config": {
        "weight_fast": 1.0,
        "weight_plddt": 5.0,
        "weight_iptm": 1.0,
        "weight_ptm": 0.5,
        "weight_interface_plddt": 1.0,
        "weight_node_plddt_min": 0.5,
        "weight_clash": 1.0,
        "weight_multistate": 1.0,
        "plddt_scale": 100.0,
        "clash_scale": 10.0,
        "fast_loss_nonneg": True,
    },
}


def base_strategy() -> Dict[str, Any]:


    return deepcopy(_BASE_STRATEGY)
